USE website;

TRUNCATE players;
TRUNCATE player_stats;
TRUNCATE games;
TRUNCATE teams;

LOAD DATA INFILE 'Players.txt'
INTO TABLE players
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\r\n';

LOAD DATA INFILE 'Player_Stats.txt'
INTO TABLE players_stats
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\r\n';

LOAD DATA INFILE 'Games.txt'
INTO TABLE games
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\r\n';

LOAD DATA INFILE 'Teams.txt'
INTO TABLE teams
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\r\n';


SELECT * FROM transactions;
DESCRIBE transactions;