USE fantasy;

TRUNCATE players;
TRUNCATE player_stats;
TRUNCATE games;
TRUNCATE teams;

LOAD DATA INFILE 'Players.txt'
INTO TABLE players
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

LOAD DATA INFILE 'Player_Stats.txt'
INTO TABLE player_stats
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

LOAD DATA INFILE 'Games.txt'
INTO TABLE games
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

LOAD DATA INFILE 'Teams.txt'
INTO TABLE teams
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\r\n';

